name: Canopy_height_env
channels:
  - defaults
dependencies:
  - python=3.11 
  - pip
  - pip:
      - gdown
      - torch
      - numpy
      - pandas
      - pillows
      - rasterio
      - albumentations
      - tqdm
      - matplotlib
